### ISSUE TITLE
Can't reproduce the results

### ISSUE THREAD

**Issue by yifanjiang19** [PistonY/ModelZoo.pytorch#5]
Hi,

Thanks for sharing this great work. I try to run you command to reproduce ghostnet but I'm only able to get around 74.7%, which should be >75%. Is there any suggestions? Here is the command I use:
```
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python distribute_train_script.py --data-path /workspace/datasets/ImageNet/decompressed/t1/ --batch-size 256 --dtype float16 \
                                  -j 48 --epochs 360 --lr 2.6 --warmup-epochs 5 --label-smoothing \
                                  --no-wd --wd 0.00003 --model GhostNet --log-interval 150 --model-info \
                                  --dist-url tcp://127.0.0.1:26548 --world-size 1 --rank 0
```

**Comment by yifanjiang19** [comment]
Seems to be the batch size issue. Close issue

**Comment by DevinXYang** [comment]
Hi, @yueruchen 
I also share the train log and param on Google Drive, you can compare to yourself when you training.
